# 環境変数でSPRING_PROFILES_ACTIVE=application.ymlのsuffix

spring:
  thymeleaf:
    mode: HTML
    cache: false
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
  jpa:
    open-in-view: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: false
          
        

